# Generated by Django 2.1.7 on 2020-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la Categoría', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='sintoma',
            field=models.ManyToManyField(to='cnv.Sintoma'),
        ),
    ]
